#!/usr/bin/env bash
# 【最终操作指南】修复仿真中的 /odom 话题问题

echo "════════════════════════════════════════════════════════════════════════"
echo "               tri_steer_odom 修复 - 最终操作指南"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "🔴 【当前问题】"
echo "  • /odom 话题存在但为空（无数据）"
echo "  • 可能原因：tri_steer_odom 未启动或数据被过度过滤"
echo ""

echo "🟡 【快速修复步骤】"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "【步骤 1】验证仿真运行（必须）"
echo "─────────────────────────────────────"
echo "命令：rostopic list | grep -E 'clock|joint_states'"
echo ""
echo "✅ 预期输出应该包含："
echo "   /clock"
echo "   /joint_states"
echo ""
echo "❌ 如果没有，需要先启动仿真："
echo "   cd /home/cfl/RealSlamRos1"
echo "   ./sim_minimal.sh"
echo ""
echo "按 Enter 继续..."
read -t 30 || true
echo ""

echo "【步骤 2】重新编译代码（因为修改了参数）"
echo "─────────────────────────────────────"
echo "命令："
echo "  cd /home/cfl/RealSlamRos1"
echo "  catkin_make -j4"
echo ""
echo "按 Enter 继续..."
read -t 60 || true
echo ""

echo "【步骤 3】启动导航节点（带调试模式）"
echo "─────────────────────────────────────"
echo "在新终端运行："
echo "  cd /home/cfl/RealSlamRos1"
echo "  source devel/setup.bash"
echo "  roslaunch robot_navigation motionPlan_sim_debug.launch debug:=true"
echo ""
echo "✅ 预期输出："
echo "   [INFO] tri_steer_odom 已启动！"
echo "   [INFO] 处理第 100 帧  <- 调试信息"
echo ""
echo "按 Enter 继续..."
read -t 60 || true
echo ""

echo "【步骤 4】监测 /odom 数据（在另一个新终端）"
echo "─────────────────────────────────────"
echo "命令："
echo "  cd /home/cfl/RealSlamRos1 && source devel/setup.bash"
echo "  timeout 10 rostopic echo /odom -n 5"
echo ""
echo "✅ 成功标志："
echo "   pose:"
echo "     pose:"
echo "       position:"
echo "         x: 0.0"
echo "         y: 0.0"
echo "       orientation: {}"
echo "   twist:"
echo "     twist:"
echo "       linear:"
echo "         x: 0.0"
echo "         y: 0.0"
echo ""
echo "❌ 失败标志："
echo "   WARNING: no messages received and simulated time is active."
echo ""
echo "按 Enter 继续..."
read -t 60 || true
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "             【故障排查】如果仍然无数据"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "【检查1】节点是否在运行"
echo "─────────────────────────────────────"
echo "命令: rosnode list | grep tri_steer_odom"
echo ""
echo "✅ 应该看到: /tri_steer_odom"
echo "❌ 如果没看到，需要检查启动是否失败"
echo ""

echo "【检查2】/joint_states 数据质量"
echo "─────────────────────────────────────"
echo "命令: rostopic echo /joint_states -n 1 | grep -A 10 position"
echo ""
echo "✅ 正常范围："
echo "   position 值应该在 -3.14 ~ 3.14 之间"
echo "   velocity 值应该在 -100 ~ 100 之间"
echo ""
echo "❌ 异常示例："
echo "   position: -7353.06  <- 编码器累积值！"
echo "   velocity: -867.62"
echo ""
echo "如果看到异常值，这说明编码器配置有根本问题"
echo ""

echo "【检查3】是否有异常警告"
echo "─────────────────────────────────────"
echo "在运行导航节点的终端中查看是否有："
echo "  [WARN] tri_steer_odom 数据异常"
echo "  [WARN] 关节读取失败"
echo ""
echo "如果有这些警告，说明数据被过滤了"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "                 【参数调优】如果数据被过度过滤"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "编辑文件: /home/cfl/RealSlamRos1/src/robot_navigation/scripts/tri_steer_odom.py"
echo ""
echo "修改这些参数（搜索关键字）："
echo ""
echo "# 如果异常检查过于严格，可以放宽阈值（搜索 '数据有效性检查'）"
echo "if abs(w) > 100.0:      # 从 100.0 改为 150.0 或 200.0"
echo "if abs(s) > 10 * math.pi: # 从 10π 改为 15π 或 20π"
echo ""
echo "# 如果低通滤波响应太慢，可以调整（搜索 'alpha ='）"
echo "alpha = 0.4  # 改为 0.3 或 0.2（更敏感）"
echo ""
echo "修改后需要重新编译："
echo "  cd /home/cfl/RealSlamRos1 && catkin_make"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "                    【自动测试脚本】"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "运行完整诊断（需要仿真已启动）："
echo "  bash /home/cfl/RealSlamRos1/diagnose_odom_empty.sh"
echo ""

echo "运行快速诊断："
echo "  bash /home/cfl/RealSlamRos1/quick_odom_check.sh"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "                    【关键文件位置】"
echo "════════════════════════════════════════════════════════════════════════"
echo ""

echo "修改的核心文件："
echo "  /home/cfl/RealSlamRos1/src/robot_navigation/scripts/tri_steer_odom.py"
echo ""

echo "调试用的 launch 文件："
echo "  /home/cfl/RealSlamRos1/src/robot_navigation/launch/motionPlan_sim_debug.launch"
echo ""

echo "诊断脚本："
echo "  /home/cfl/RealSlamRos1/diagnose_odom_empty.sh"
echo "  /home/cfl/RealSlamRos1/quick_odom_check.sh"
echo ""

echo "════════════════════════════════════════════════════════════════════════"
echo "完毕！"
echo "════════════════════════════════════════════════════════════════════════"
