#!/bin/bash

# 📋 IMU+激光融合里程计系统 - 文件导航

echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        IMU+激光融合里程计系统 - 完整文件导航                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# 定义颜色
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}🚀 启动脚本${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  1. sim_lidar_imu_fusion.sh"
echo "     ├─ 功能: 一键启动完整仿真系统"
echo "     ├─ 启动: ./sim_lidar_imu_fusion.sh"
echo "     └─ 包含: Gazebo + IMU + 融合 + Cartographer + RViz"
echo ""

echo -e "${GREEN}📊 检查工具${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  2. check_imu_fusion.sh"
echo "     ├─ 功能: 系统健康检查"
echo "     ├─ 启动: ./check_imu_fusion.sh"
echo "     └─ 验证: 所有话题、节点、频率是否正常"
echo ""

echo -e "${GREEN}🖥️  实时监控${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  3. fusion_monitor.py"
echo "     ├─ 功能: 实时监控仪表板"
echo "     ├─ 启动: rosrun robot_navigation fusion_monitor.py"
echo "     └─ 显示: 位置、速度、IMU、激光数据"
echo ""

echo -e "${GREEN}📚 文档${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  4. IMU_LIDAR_FUSION_README.md"
echo "     ├─ 内容: 完整技术文档"
echo "     ├─ 章节: 系统架构、参数调优、故障排查"
echo "     └─ 查看: cat IMU_LIDAR_FUSION_README.md | less"
echo ""

echo "  5. QUICKSTART_FUSION.md"
echo "     ├─ 内容: 快速开始指南"
echo "     ├─ 重点: 5分钟上手"
echo "     └─ 查看: cat QUICKSTART_FUSION.md"
echo ""

echo "  6. SOLUTION_SUMMARY.md"
echo "     ├─ 内容: 解决方案总结"
echo "     ├─ 重点: 问题分析、设计原理"
echo "     └─ 查看: cat SOLUTION_SUMMARY.md"
echo ""

echo -e "${GREEN}💻 核心节点代码${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  7. src/robot_navigation/scripts/imu_lidar_fusion_odom.py"
echo "     ├─ 功能: IMU+激光融合里程计主节点"
echo "     ├─ 行数: 287行"
echo "     └─ 发布: /odom, /odom→/base_footprint TF"
echo ""

echo "  8. src/robot_navigation/scripts/virtual_imu_publisher.py"
echo "     ├─ 功能: 虚拟IMU传感器发布器"
echo "     ├─ 行数: 156行"
echo "     └─ 发布: /imu"
echo ""

echo -e "${GREEN}⚙️  配置文件${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo "  9. src/robot_navigation/launch/imu_lidar_fusion.launch"
echo "     ├─ 功能: ROS Launch配置"
echo "     └─ 参数: lidar_weight, imu_weight, update_rate"
echo ""

echo ""
echo -e "${YELLOW}🎯 快速开始流程${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo -e "${BLUE}第1步: 启动系统${NC}"
echo "  $ cd ~/RealSlamRos1"
echo "  $ ./sim_lidar_imu_fusion.sh"
echo ""
echo -e "${BLUE}第2步: 验证状态（另开终端）${NC}"
echo "  $ ./check_imu_fusion.sh"
echo ""
echo -e "${BLUE}第3步: 实时监控（第3个终端）${NC}"
echo "  $ rosrun robot_navigation fusion_monitor.py"
echo ""
echo -e "${BLUE}第4步: 在RViz中可视化（第4个终端）${NC}"
echo "  $ rviz"
echo "  • 添加 TF 插件查看变换"
echo "  • 添加 Odometry 插件查看位置"
echo "  • 添加 PointCloud2 (topic: /scan) 查看激光"
echo ""

echo ""
echo -e "${YELLOW}🔧 参数调优参考${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo -e "${BLUE}场景1: 小车仍有细微运动${NC}"
echo "  修改权重为激光优先:"
echo "  $ roslaunch robot_navigation imu_lidar_fusion.launch \\"
echo "      lidar_weight:=0.8 imu_weight:=0.2"
echo ""
echo -e "${BLUE}场景2: 转向响应不足${NC}"
echo "  增加IMU权重:"
echo "  $ roslaunch robot_navigation imu_lidar_fusion.launch \\"
echo "      lidar_weight:=0.5 imu_weight:=0.5"
echo ""
echo -e "${BLUE}场景3: 噪声过大${NC}"
echo "  降低虚拟IMU噪声:"
echo "  $ rosrun robot_navigation virtual_imu_publisher.py \\"
echo "      _gyro_noise:=0.005 _accel_noise:=0.02"
echo ""

echo ""
echo -e "${YELLOW}📊 关键话题和命令${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo -e "${BLUE}查看话题${NC}"
echo "  # 融合里程计（位置+速度+方向）"
echo "  $ rostopic echo /odom"
echo ""
echo "  # 虚拟IMU数据（角速度+加速度）"
echo "  $ rostopic echo /imu"
echo ""
echo "  # 激光扫描"
echo "  $ rostopic echo /scan -n 1"
echo ""

echo -e "${BLUE}检查频率${NC}"
echo "  # 应该显示 ~50 Hz"
echo "  $ rostopic hz /odom"
echo ""
echo "  # 应该显示 ~20 Hz"
echo "  $ rostopic hz /imu"
echo ""

echo -e "${BLUE}调试工具${NC}"
echo "  # 显示所有节点"
echo "  $ rosnode list"
echo ""
echo "  # 显示所有话题"
echo "  $ rostopic list"
echo ""
echo "  # 可视化TF树"
echo "  $ rosrun tf view_frames && evince frames.pdf"
echo ""
echo "  # 监控TF链"
echo "  $ rosrun tf tf_monitor"
echo ""

echo ""
echo -e "${YELLOW}🛠️  常见问题${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo -e "${RED}Q: /odom 没有数据？${NC}"
echo "  A: 检查虚拟IMU是否运行"
echo "     $ rosnode list | grep virtual_imu"
echo ""

echo -e "${RED}Q: TF树仍然断裂？${NC}"
echo "  A: 检查融合节点是否正常工作"
echo "     $ rosrun tf view_frames"
echo ""

echo -e "${RED}Q: 小车仍在自主移动？${NC}"
echo "  A: 调整参数，增加激光权重或降低IMU噪声"
echo ""

echo -e "${RED}Q: 性能太低？${NC}"
echo "  A: 降低更新频率"
echo "     <param name=\"update_rate\" value=\"20\" />"
echo ""

echo ""
echo "─────────────────────────────────────────────────────────────────"
echo -e "${GREEN}✅ 系统已完全配置就绪！${NC}"
echo "─────────────────────────────────────────────────────────────────"
echo ""
echo "📞 需要帮助？"
echo "  1. 查看 QUICKSTART_FUSION.md （5分钟快速开始）"
echo "  2. 查看 IMU_LIDAR_FUSION_README.md （完整文档）"
echo "  3. 查看 SOLUTION_SUMMARY.md （设计原理）"
echo "  4. 运行 check_imu_fusion.sh （系统检查）"
echo ""
